repositories:
  gz-cmake:
    type: git
    url: https://github.com/gazebosim/gz-cmake
    version: gz_cmake_project
  gz-common:
    type: git
    url: https://github.com/gazebosim/gz-common
    version: gz_cmake_project
  gz-math:
    type: git
    url: https://github.com/gazebosim/gz-math
    version: gz_cmake_project
  gz-plugin:
    type: git
    url: https://github.com/gazebosim/gz-plugin
    version: gz_cmake_project
  gz-utils:
    type: git
    url: https://github.com/gazebosim/gz-utils
    version: gz_cmake_project
