repositories:
  gz-cmake:
    type: git
    url: https://github.com/ignitionrobotics/ign-cmake
    version: gz_cmake_project
  gz-math:
    type: git
    url: https://github.com/ignitionrobotics/ign-math
    version: gz_cmake_project
  gz-utils:
    type: git
    url: https://github.com/ignitionrobotics/ign-utils
    version: gz_cmake_project
