name: Ubuntu CI

on: [push, pull_request]

jobs:
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@chapulina/focal/before_dep
        with:
          tests-enabled: false
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@jammy
        with:
          tests-enabled: false
